#include <string.h>
#include <limits.h>
#include <unistd.h>

#include "tstate.h"


/* 
 * Internal frequency table 
 * Generated by scanning my personal home directory...
 * TODO(jure): clamp these values for better readability
 */
static const size_t internal_freqs[TIGHTBYTES] = {
	19545057148, 3531108214, 1608094686, 1345198511, 1051892339, 1281745510,
	1025513827, 1293687674, 1074268988, 1039079184, 1506712383, 1006938116,
	795036552, 819284256, 852720474, 968347569, 1196237159, 807296250,
	786485745, 731167573, 781870300, 763658141, 738518199, 758042149,
	829081582, 685694952, 678796172, 676470373, 702196128, 666433739,
	683222022, 736999294, 2958994857, 779549982, 970811770, 748844265,
	2791295041, 782214617, 749453427, 746809483, 901992964, 854420995,
	853510029, 752541364, 862078787, 895318580, 871196875, 996286245,
	1142965387, 951312275, 897361636, 832370440, 833594196, 877280491,
	816667022, 818486808, 852146631, 857172604, 853105995, 776436170,
	846287620, 806242722, 824778664, 891514664, 1568753874, 978313472,
	853034202, 828046685, 951234698, 904186093, 765447813, 721993000,
	952508445, 2772622197, 763032728, 707757167, 809345295, 784046744,
	779820569, 748080777, 916397991, 741497902, 895733761, 825590259,
	921582190, 1410512585, 779314963, 852379720, 829165307, 710956480,
	776220169, 721986867, 755255426, 745245184, 763461684, 1211140497,
	1227317123, 1180594804, 925826420, 1026633696, 1017023507, 1432370508,
	918557547, 816561729, 918723200, 1164397897, 777094249, 792277091,
	1016234870, 960079981, 1126487943, 1098093242, 978665597, 721869246,
	1191747305, 1138392234, 1264131985, 955209081, 833546979, 843656902,
	904019433, 781422670, 816126058, 791862043, 720578188, 765742304,
	788591215, 1147773006, 1712655311, 817868332, 844748524, 823909767,
	812708759, 736280498, 745345572, 701548435, 802590272, 884113835,
	786187744, 858603931, 734290325, 788617276, 705835575, 717950119,
	848129761, 713005070, 2568746106, 705717055, 759590307, 752072442,
	717126578, 711291732, 729814559, 712423716, 696898312, 704859226,
	709502527, 676758481, 677280091, 689800715, 1242406300, 685941610,
	763057463, 701885520, 731867652, 743022578, 716962124, 702450609,
	822948599, 753694915, 1518687795, 827312002, 727994792, 824051557,
	763994388, 815026818, 721157140, 673981331, 688732575, 669665978,
	699130050, 853058759, 764322091, 728838860, 702351647, 685593462,
	761087802, 743002265, 687169052, 845386414, 755058012, 849555754,
	1379241633, 673989477, 680363645, 699588927, 691508678, 680381279,
	717122561, 730331068, 688976887, 719295107, 686018355, 698392536,
	715046721, 708421468, 717085182, 703626425, 745836891, 675432857,
	674991176, 674358242, 667656210, 845247119, 734289225, 776049057,
	707136643, 669937268, 691263779, 745442244, 703373116, 746489879,
	740342449, 775085830, 1481481747, 652846418, 689050812, 690898299,
	684159252, 680178686, 688683763, 734799744, 798865773, 715575417,
	805350383, 776156546, 695178132, 739140401, 792396706, 813911924,
	795949588, 702618702, 672532244, 704033862, 682235836, 840446583,
	748366370, 809374385, 967943703, 818837829, 1044098607, 1498659876,
	1565985814, 1125047180, 1200921949, 3807361529, 
};


/* header magic */
const byte MAGIC[8] = { 
	0x54, 0x49, 0x47, 0x48, 0x54, /* T I G H T */
	0x00, 0x00, 0x00, /* padding */
};


typedef struct TreeHeap {
	TreeData *trees[TIGHTBYTES*2]; /* trees */
	int len; /* number of elements in 'trees' */
} TreeHeap;



/* create state */
TIGHT_API tight_State *tight_new(tight_fRealloc frealloc, void *userdata) {
	tight_State *ts = (tight_State *)frealloc(NULL, userdata, 0, SIZEOFSTATE);
	if (t_unlikely(ts == NULL))
		return NULL;
	ts->frealloc = frealloc;
	ts->ud = userdata;
	ts->fmsg = NULL;
	ts->fpanic = NULL;
	ts->hufftree = NULL;
	memset(ts->codes, 0, sizeof(ts->codes));
	ts->rfd = ts->wfd = -1;
	return ts;
}


/* set error writer */
TIGHT_API tight_fError tight_seterror(tight_State *ts, tight_fError fmsg) {
	tight_fError old = ts->fmsg;
	ts->fmsg = fmsg;
	return old;
}


/* set panic handler */
TIGHT_API tight_fPanic tight_setpanic(tight_State *ts, tight_fPanic fpanic) {
	tight_fPanic old = ts->fpanic;
	ts->fpanic = fpanic;
	return old;
}


/* delete state */
TIGHT_API void tight_free(tight_State *ts) {
	if (ts->hufftree) 
		tightT_freeparent(ts, ts->hufftree);
	ts->frealloc(ts, ts->ud, SIZEOFSTATE, 0);
}


/* swap */
static inline void swap_(TreeData **x, TreeData **y) {
	TreeData *temp = *x;
	*x = *y;
	*y = temp;
}


/* sort tree data */
static void tightqsort(TreeData **v, int start, int end) {
	if (start >= end) return;
    swap_(&v[start], &v[(start + end) >> 1]); /* move pivot to start */
    int last = start;
    for(int i = last + 1; i <= end; i++)
        if (v[i]->freq > v[start]->freq)
            swap_(&v[++last], &v[i]);
    swap_(&v[start], &v[last]);
	tightqsort(v, start, last - 1);
	tightqsort(v, last + 1, end);
}


/* binary search */
static unsigned int getsortedindex(TreeData **v, int l, int h, TreeData *td) {
	int mid;

	while (l < h) {
		mid = (l + h) >> 1;
		if (v[mid]->freq > td->freq) l = mid;
		else h = mid;
	}
	return mid;
}


/* insert tree into tree heap */
static void sortedinsert(TreeHeap *ht, TreeData *td) {
	unsigned int i = getsortedindex(ht->trees, 0, ht->len - 1, td);
	memmove(&ht->trees[i + 1], &ht->trees[i], ht->len - i);
	ht->trees[i] = td;
	ht->len++;
}


/* reverse bits */
static inline unsigned reversebits(unsigned code, int len) {
	register unsigned res;
	t_assert(len > 0);
	do {
		res |= code & 1;
		code >>= 1;
		res <<= 1;
	} while (len-- > 0);
	return res >> 1;
}


/* generate huffman codes table and build huffman tree */
static void gencodes(tight_State *ts, const size_t *freqs) {
	TreeHeap ht = { 0 }; /* huffman tree stack */
	size_t combfreqs[TIGHTCODES]; /* freqs + combined frequencies */
	int parentindexes[TIGHTCODES]; /* parent frequency indexes in 'combfreqs' */
	TreeData *t1, *t2; /* left/right subtree */
	int fi = TIGHTBYTES; /* next available position in 'combfreqs' */
	int i; /* loop counter */

	/* copy over counts */
	mempcpy(combfreqs, freqs, TIGHTBYTES);
	memset(&combfreqs[TIGHTBYTES], 0, TIGHTBYTES);

	/* make leafs */
	for (i = 0; i < TIGHTBYTES; i++)
		if (combfreqs[i] != 0)
			ht.trees[ht.len++] = tightT_newleaf(ts, combfreqs[i], i);

	/* sort leaf trees */
	tightqsort(ht.trees, 0, ht.len - 1);

	/* build huffman tree and frequency array */
	while (ht.len > 1) {
		t1 = ht.trees[--ht.len]; /* left subtree */
		t2 = ht.trees[--ht.len]; /* right subtree */
		sortedinsert(&ht, tightT_newparent(ts, t1, t2, fi)); /* t1 <- p -> t2 */
		combfreqs[fi] = t1->freq + t2->freq;
		parentindexes[t1->c] = -fi; /* left */
		parentindexes[t2->c] = fi; /* right */
		fi++; /* advance index into 'combfreqs' */
	}
	t_assert(sb.len == 1);
	t1 = ht.trees[--ht.len]; /* pop huffman tree */
	parentindexes[t1->c] = t1->c; /* mark as no parent (root) */
	ts->hufftree = t1; /* anchor to state */

	/* build huffman codes */
	int nbits, code, y;
	for (i = 0; i < TIGHTBYTES; i++) {
		if (combfreqs[i] == 0) /* skip 0 frequency bytes */
			continue;
		y = i; /* preserve 'i' */
		nbits = code = 0;
		/* build the huffman code */
		while (t_abs(parentindexes[y]) != y) { /* while not tree root */
			code |= (parentindexes[y] >= 0) << nbits; /* 1 if right, 0 if left */
			y = t_abs(parentindexes[y]); /* follow the node to root */
			nbits++; /* increment number of bits in 'code' */
		}
		t_assert(nbits > 0);
		ts->codes[i].code = reversebits(code, nbits);
		ts->codes[i].nbits = nbits;
	}
}


/* 
 * Set input and output file descriptors and generate
 * huffman codes table based on provided frequencies.
 * 'freqs' must be of size 256 (or TIGHTBYTES).
 * In case 'freqs' is NULL then internal frequency table
 * is used 'internal_freqs'.
 */
TIGHT_API void tight_setfiles(tight_State *ts, int rfd, int wfd, const size_t *freqs) {
	t_assert(rfd >= 0 && wfd >= 0 && rfd != wfd);
	if (ts->hufftree)
		tightT_freeparent(ts, ts->hufftree);
	memset(ts->codes, 0, sizeof(ts->codes));
	ts->rfd = rfd;
	ts->wfd = wfd;
	gencodes(ts, freqs ? freqs : internal_freqs);
}
